plugins:
  - jest
env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: off
  import/extensions: #удалить, когда в новой версии nodejs это правило исправят
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]